# Generated by Django 3.1.3 on 2020-11-15 13:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scraping', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='News',
            new_name='NewsArticle',
        ),
    ]
