# Generated by Django 3.1.3 on 2020-11-15 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraping', '0002_auto_20201115_1351'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newsarticle',
            name='body',
            field=models.TextField(max_length=10000),
        ),
    ]
