# Generated by Django 3.1.3 on 2020-11-15 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraping', '0003_auto_20201115_1352'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newsarticle',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
